// Signing and packaging of extension bundles, format `haextension-bundle/2` (Node.js only).
import { webcrypto } from "crypto";
import * as fs from "fs/promises";
import * as path from "path";
import { getExtensionDir, readHaextensionConfig } from "~/config";
import { readManifest } from "~/manifest";
import {
  BUNDLE_FILE_EXTENSION,
  BundleError,
  buildBundle,
  maxBundleBytes,
  verifyBundle,
  type BundleEntry,
  type BundleErrorKind,
  type SignedFile,
  type VerifiedBundle,
} from "~/bundle";

export const EXTENSION_FILE_EXTENSION = BUNDLE_FILE_EXTENSION;

export type PackageVerifyResult =
  | { valid: true; manifest: Record<string, unknown>; files: SignedFile[] }
  | { valid: false; kind: BundleErrorKind | "io_error"; path?: string; error: string };

/** Files of the extension directory that never go into a bundle or are generated by signing. */
const EXTENSION_DIR_SKIPPED = new Set(["manifest.json", "signature.json", "public.key", "private.key"]);

export class ExtensionSigner {
  /** Generates an Ed25519 keypair: raw public key and PKCS#8 private key, both hex. */
  static async generateKeypair(): Promise<{ publicKey: string; privateKey: string }> {
    const keypair = (await webcrypto.subtle.generateKey({ name: "Ed25519" }, true, [
      "sign",
      "verify",
    ])) as unknown as CryptoKeyPair;
    const publicKeyBuffer = await webcrypto.subtle.exportKey("raw", keypair.publicKey);
    const privateKeyBuffer = await webcrypto.subtle.exportKey("pkcs8", keypair.privateKey);
    return {
      publicKey: Buffer.from(publicKeyBuffer).toString("hex"),
      privateKey: Buffer.from(privateKeyBuffer).toString("hex"),
    };
  }

  /**
   * Collects the regular files below `rootDir` with `lstat`, so a symlink is
   * never followed: it aborts packaging, as does any other non-regular file.
   * Paths are relative to `rootDir`, `/`-separated and prefixed with `prefix`.
   */
  static async collectFilesAsync(
    rootDir: string,
    prefix = "",
    skip: (relativePath: string) => boolean = () => false,
  ): Promise<BundleEntry[]> {
    const entries: BundleEntry[] = [];
    const walk = async (dir: string): Promise<void> => {
      for (const name of await fs.readdir(dir)) {
        const fullPath = path.join(dir, name);
        const relative = path.relative(rootDir, fullPath).split(path.sep).join("/");
        const stats = await fs.lstat(fullPath);
        if (stats.isSymbolicLink()) {
          throw new BundleError("entry_kind", `symlinks are not allowed in a bundle: ${fullPath}`, relative);
        }
        if (stats.isDirectory()) {
          await walk(fullPath);
        } else if (!stats.isFile()) {
          throw new BundleError("entry_kind", `not a regular file: ${fullPath}`, relative);
        } else if (!skip(relative)) {
          entries.push({ path: `${prefix}${relative}`, data: new Uint8Array(await fs.readFile(fullPath)) });
        }
      }
    };
    await walk(rootDir);
    return entries;
  }

  /**
   * Builds, signs and writes a v2 bundle from the build output `extensionPath`,
   * the extension directory (manifest and extra files, never keys) and the
   * migrations, then verifies the written file. Returns the output path.
   */
  static async packageExtension(extensionPath: string, privateKeyHex: string, outputPath?: string): Promise<string> {
    const rootDir = process.cwd();
    const extensionDir = getExtensionDir(rootDir);
    const manifest = readManifest({ rootDir, extensionDir });
    if (!manifest) throw new Error("Failed to read manifest.json");

    const files = await this.collectFilesAsync(extensionPath);
    files.push(
      ...(await this.collectFilesAsync(path.resolve(rootDir, extensionDir), "haextension/", (relative) =>
        EXTENSION_DIR_SKIPPED.has(relative),
      )),
    );

    // `./db/` and `db` name the same folder; the manifest and the bundle paths must both use `db`.
    manifest.migrationsDir = manifest.migrationsDir?.replace(/^(?:\.\/)+/, "").replace(/\/+$/, "") || null;
    if (manifest.migrationsDir) {
      const config = readHaextensionConfig(rootDir);
      const sourceDir = config?.build?.migrationsSourceDir || `app/${manifest.migrationsDir}`;
      const sourcePath = path.resolve(rootDir, sourceDir);
      const exists = await fs.stat(sourcePath).then(
        (stats) => stats.isDirectory(),
        () => false,
      );
      if (exists) {
        files.push(...(await this.collectFilesAsync(sourcePath, `${manifest.migrationsDir}/`)));
        console.log(`✓ Adding migrations from ${sourceDir} as ${manifest.migrationsDir}`);
      } else {
        console.warn(`⚠ Migrations directory not found: ${sourcePath}`);
      }
    }

    const privateKey = privateKeyHex.trim();
    if (!/^(?:[0-9a-fA-F]{2})+$/.test(privateKey)) throw new Error("private key is not hex");
    // Signs, writes the archive and verifies it like a host before returning it.
    const archive = buildBundle(
      files,
      manifest as unknown as Record<string, unknown>,
      Buffer.from(privateKey, "hex"),
    );
    const finalOutputPath = outputPath || `${manifest.name}-${manifest.version}${BUNDLE_FILE_EXTENSION}`;
    await fs.writeFile(finalOutputPath, archive);
    console.log(`✓ Extension packaged: ${finalOutputPath} (${files.length + 2} files)`);
    return finalOutputPath;
  }

  /** Reads and verifies a `.xt` file; throws a `BundleError` naming the first failing rule. */
  private static async verifyFileAsync(packagePath: string): Promise<VerifiedBundle> {
    const { size } = await fs.stat(packagePath);
    if (size > maxBundleBytes()) {
      throw new BundleError("archive_too_large", `archive is larger than ${maxBundleBytes()} bytes`);
    }
    return verifyBundle(await fs.readFile(packagePath));
  }

  /** Verifies a `.xt` file exactly like a host does (bundle format v2). */
  static async verifyPackage(packagePath: string): Promise<PackageVerifyResult> {
    try {
      const { manifest, files } = await this.verifyFileAsync(packagePath);
      return { valid: true, manifest, files };
    } catch (error) {
      if (error instanceof BundleError) {
        return { valid: false, kind: error.kind, path: error.path, error: error.message };
      }
      // Only a failing file system call is an I/O error; anything else is a bug and propagates.
      if (error instanceof Error && "code" in error) {
        return { valid: false, kind: "io_error", error: error.message };
      }
      throw error;
    }
  }
}
